OpenTemplot Persistence Framework
=================================

CAUTION: This framework is experimental and subject to change!

The OpenTemplot Persistence Framework is a framework developed in Free Pascal to provide a number of basic services to applications.

* saving and restoring objects in YAML files
* fine-grained undo/redo
* on-demand recalculation of objects
* automated generation of boiler-plate code.

== Outline of usage

All persistent objects need to be descendant classes of `TOTPersistent`, and the source files created using the `codegen` tool. Properties of the class that are to be persisted need to be defined in a comment section at the head of the file using a YAML structure defined later. The `codegen` tool reads the YAML data, and generates all the boiler-plate code required by the framework.

=== Steps to create a new class
.Ordered
. Use `codegen` to create a new unit
+
----
> codegen new class SwitchInfo
----
+
This creates a new unit named `switchinfo.pas`. This unit contains the class TSwitchInfo.

. Add the new unit to your project

. Define properties of the class in the YAML block at the head of the file. The initial block will look like:
+
----
{# class TSwitchInfo
---
class: TSwitchInfo
attributes:
...
}
----
+
Edit this block to include your required properties and save, for example:
+
----
{# class TSwitchInfo
---
class: TSwitchInfo
attributes:
  - name: switchPattern
    type: Integer
  - name: planingLength
    type: Double
  - name: planingAngle
    type: Double
  - name: switchRadius
    type: Double
  - name: switchRailLength
    type: Double
    comment: (C) length of switch rail (inches)
...
}
----

. Run `codegen` again to generate code for the class:
+
----
> codegen gen switchinfo.pas
----

When you need to change or add more properties to a class, repeat the edit and `codegen` steps to regenerate the boiler-plate code.

== Codegen Attributes YAML 

The YAML defines a sequence of attributes. Each attribute is a map containing the following name/value pairs:

=== name
This is the attribute name, expected to be in camelCase. This name will be used directly to a property in the class. Variations of the name will be used for the backing variable, get/set methods and list-related methods.

=== type
The Pascal type for the property. `Integer`, `Double` and `String` are supported directly. Other types can be specified if appropriate supporting methods (for conversion to/from string) are provided.

=== access
Controls access to the property. Value is a set containing either `get`, `set`, or both. If not specified, the default is both.

=== owns
If present, this specifies the property is referring to another `TOTPersistent` object. Values are `own` or `ref`. A value of `own` specifies a parent-child relation, and the lifetime of the child object will be tied to the parent. A value of `ref` specifies this is purely a reference. Child objects will be stored in YAML as a sub-oject of the parent.

=== array
Specifies if this is an array property. Values are `false`, `dynamic`, a range that includes `..` or an enumerated type name.

* `false` specifices this is *not* an array property

* `dynamic` specifies a dynamic (resizable) array. If this is selected a `<name>Count` property will be created. The `operations` entry applies only to dynamic arrays.

* `..` range and enumerated type define a fixed-size array property. Get and Set methods will take an index of the appropriate type but no Count method will be created, and no operations are supported.

=== operations
Specifies a set of operations that will be generated for a `dynamic` array. The set is a sequence of strings, with allowed values of `add`, `delete` and `clear`.

Example:
----
  - name: sample
    type: Integer
    array: dynamic
    operations: [add, clear]
----

This will generate `AddSample` and `ClearSample` methods.

=== comment
Defines a comment that included with the property definition (that may then get picked up by PasDoc). The comment can be either a single line comment, or a multiline block comment.

Example:
----
  - name: sample
    type: String
    comment: |
      A multi-line comment
      about sample
      (not necessarily very complimentary)
----

== Saving/Restoring Objects to YAML

In order for the Framework to save objects as YAML and restore from YAML, all persistent classes must descend from `TOTPersistent`. The `TOTPersistent` class contains methods for saving and restoring to YAML that manage the emitting and parsing of YAML. `TOTPersistent` will call virtual methods to manage saving and restore of class attributes to YAML. These methods are automatically generated by the `codegen` tool.

Architecturally, an application should have a single instance of a top-level project class that owns all the objects related to the project. For OpenTemplot, that will be a `TProject` class that owns all the templates and other objects within the project. When the top-level instance is saved to YAML, all other owned-objects will also be saved recursively.

YAML files will be versioned, and upgrading will be handled by loading the YAML file into a YAML DOM (Document Object Model), and processing that as required to perform any upgrades. Once upgraded, the YAML will be restored normally.

== Fine-grained Undo/Redo

In addition to the saving/restoring YAML, the `codegen` tool also generates methods to save and restore an object from a stream in binary form. These save/restore routines are *not* recursive -- they just save the current object and not child objects. The intent is to have a transaction-based UndoRedoManager that will save an object whenever it is modified (tracked automatically by boiler-plate code) to a stream, and be able to restore that object if an Undo operation is performed.

As the undo/redo stream is not intended for long-term persistence, there is no requirement for this to be versioned.

== Handles for Objects

As objects may be created/deleted by the undo/redo processing, we need to be able to keep track of these changes in other classes that may reference them. To achieve this we have a system of handles for storing references, rather than direct use of pointers. Every instance of `TOTPersistent` will have a unique identifier (Object Identifier or `OID`). Any object that has a reference to another object will store the `OID` rather than a pointer. An ObjectManager will provide a mapping function to get an actual pointer given the `OID`. These pointers must never be stored, and their lifetime is limited by actions of the UndoRedoManager.

== Automatic recalculation of objects

Every `TOTPersistent` object will have a calculated state: either calculated, or not. Whenever any property of an object is modified, the state will be set to not modified. This 'not modified' state will also automatically cascade to the owner of the object, and all other objects that reference the object (and so on recursively). 

Whenever any calculated property of an object is accessed, the accessor code for that property will call the `CheckCalculated` method to perform any required calculations to bring the object up-to-date. This will allow a  minimal recalculation to be performed, as only modified objects will get recalculated.

To support this functionality, every `TOTPersistent` instance will maintain a list of all other objects that reference the instance.




